# Algoritmos secuenciales
Un algoritmo es una secuencia de pasos para ejecutar una tarea descritos en un lenguaje estructurado. Un algoritmo secuencial es su forma más sencilla, en la cual el procesamiento de los datos es una sucesión de pasos que se ejecuta uno después del otro.   


 

In [ ]:
%%writefile Hello.java
class Hello 
{ 
    public static void main(String args[]) 
    { 
      System.out.println("hello"); 
    } 
} 

Writing Hello.java


In [ ]:
!java Hello.java

hello


In [ ]:
print("hello")

hello


## Primer ejemplo

Recordemos en un ejemplo muy básico como podemos leer un dato, procesarlo y mostrar el resultado. Vamos a leer un dato entero, sumarle uno y mostrarlo al usuario.

In [ ]:
print("Digite un número entero")
n = int(input())
p = round(n + 1.9)
print("El resultado es",p)

Digite un número entero
8
El resultado es 10


In [ ]:
print("Digite un número real")
print("El resultado es",float(input()) + 1.8)

Digite un número real
7
El resultado es 8.8


## Hipotenusa
Desarrollar un algoritmo que, para un triangulo recto y teniendo los dos catetos, calcule la hipotenusa.  
**Pista**: En java la raiz cuadrada: Math.sqrt(numero);   
**Pista**: En python para elevar al cuadrado es 

```
n**2  
```


**Pista**: En python para la raiz cuadrada



```
import math
math.sqrt(numero)
```

c = $\sqrt {a^2 + b^2}$

In [ ]:
import math
print("Digite los catetos")
a = int(input())  #aqui vamos a leer el cateto a
b = int(input())
a = a**2
b = b**2
c = math.sqrt(a+b)
print("La hipotenusa es",c)
#print("La hipotenusa es",math.sqrt((a**2)+(b**2)))

Digite los catetos
3
4
La hipotenusa es 5.0


In [ ]:
import math
print("Digite los catetos")
a = int(input())
b = int(input())
print("La hipotenusa es",math.sqrt((a**2)+(b**2)))

## Resistencias
Desarrollar un algoritmo que calcula la resistencia total de un circuito que tiene dos resistencias en paralelo y una tercera en serie. Recordar que para encontrar la resistencia equivalente de dos resistencias en paraleo hay que usar la siguiente formula:

RT = 1 / ((1/R1) + (1/R2))

Mientras que para resistencias en serie solo hay que sumarlas.

Pista: encontrar primero la resistencia equivalente en paralelo y después sumarla a resistencia que está en serie.


In [ ]:
print("suponga que la resistencia 1 y 2 estan en paralelo y la 3 en serie")
r1=int(input("Inserte valor en ohms de resistencia 1:"))
r2=int(input("Inserte valor en ohms de resistencia 2: "))
r3= int(input("Inserte valor en ohms de resistencia 3: "))
rt= (1/((1/r1)+(1/r2)))+r3
print("Resistencia total",rt)

suponga que la resistencia 1 y 2 estan en paralelo y la 3 en serie
Inserte valor en ohms de resistencia 1:6
Inserte valor en ohms de resistencia 2: 7
Inserte valor en ohms de resistencia 3: 8
Resistencia total 11.23076923076923


## Impuestos
Desarrollar un algoritmo para calcular el valor del impuesto de venta sobre un producto, se debe mostrar el valor del impuesto y el valor total a pagar.

In [ ]:
print("digite el valor del producto")
valorProducto = float(input())
print("digite el valor del impuesto (sin signo de porcentaje %)")
impuesto = float(input())
impuesto = impuesto/100
valorImpuesto = valorProducto * impuesto
valorTotal = valorProducto + valorImpuesto
print("El valor del impuesto es",valorImpuesto)
print("El valor total es",valorTotal)

digite el valor del producto
10
digite el valor del impuesto (sin signo de porcentaje %)
5
El valor del impuesto es 0.5
El valor total es 10.5


## Cajero

¿Cuánta plata hay en total en un cajero electrónico que maneja billetes de 50.000, 20.000 y 10.000?

In [ ]:
b10 = int(input("Inserte el número total de billetes de 10.000: "))
b20 = int(input("Inserte el número total de billetes de 20.000: "))
b50 = int(input("Inserte el número total de billetes de 50.000: "))
T10 = 10000*b10
T20 = 20000*b20
T50 = 50000*b50
TotalDinero= T10+T20+T50
print("Hay en total",TotalDinero,"pesos.")

Inserte el número total de billetes de 10.000: 1
Inserte el número total de billetes de 20.000: 1
Inserte el número total de billetes de 50.000: 1
Hay en total 80000 pesos.


In [ ]:
print ("El total de plata en el cajero",
       int(input("Inserte el número total de billetes de 10.000: ")) * 10000 +
       int(input("Inserte el número total de billetes de 20.000: ")) * 20000 +
       int(input("Inserte el número total de billetes de 50.000: ")) * 50000)

Inserte el número total de billetes de 10.000: 1
Inserte el número total de billetes de 20.000: 1
Inserte el número total de billetes de 50.000: 1
El total de plata en el cajero 80000


## Cajero2

¿Cuántos billetes de cada denominación (50.000, 20.000 y 10.000) hay que darle al cliente para un valor requerido? asumir que el valor es divisible entre 10.000

In [ ]:
#ref : https://www.w3schools.com/python/python_operators.asp
print("Digite la cantidad")
cantidad = int(input(""))
cantidadB50 = cantidad//50000
v20 = (cantidad-(cantidadB50*50000))
cantidadB20 = v20//20000
v10 = (v20-(cantidadB20*20000))
cantidadB10 = v10//10000
print("La cantidad de billetes de $50.000 es",cantidadB50)
print("La cantidad de billetes de $20.000 es",cantidadB20)
print("La cantidad de billetes de $10.000 es",cantidadB10)

Digite la cantidad
85000
Cantidad de billetes de  50k 1 20k 1 10k 1


In [ ]:
ValorRequerido = int(input("por favor digite el valor requerido: "))
Billete50 = int(ValorRequerido/50000)
ValorRequerido = ValorRequerido - (Billete50 * 50000)
Billete20 = int(ValorRequerido/20000)
ValorRequerido = ValorRequerido -(Billete20 * 20000)
Billete10 = int(ValorRequerido / 10000)
print("El numero de billetes de $50000 son " , Billete50)
print("El numero de billetes de $20000 son " , Billete20)
print("El numero de billetes de $10000 son " , Billete10)

In [ ]:
#ref : https://www.w3schools.com/python/python_operators.asp
print("Digite la cantidad")
cantidad = int (input(""))
b50= int (cantidad/50000)
print("La cantidad de billetes de 50000",b50)
cantidad= cantidad-(50000*b50)
b20=int (cantidad/20000)
print("La cantidad de billetes de 20000",b20)
cantidad= cantidad-(20000*b20)
b10= int (cantidad/10000)
print("La cantidad de billetes de 10000",b10)
cantidad= cantidad-(10000*b10)
b5=int (cantidad/5000)
print("La cantidad de billetes de 5000", b5)
cantidad=cantidad- (5000*b5)
b1=int (cantidad/1000)
print("La cantidad de billetes de 1000",b1)
cantidad=cantidad -(1000*b1)
print ("Gracias por utilizar nuestro banco")

[HackerRank secuencial](https://www.hackerrank.com/secuenciales)